project:
  type: website 

format: 
    html:
      theme: journal


website:
  title: "InsightBrasil"
  
  navbar: 
    left:
      - text: "Home"
        href: index.qmd
      - text: "Sobre"
        href: about.qmd
   

