---
project:
  type: website 

website:
  title: "Insight Brasil"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  page-footer: "Made with ❤️ and Quarto"
  navbar:
    title: William Corners
    right:

      - href: pages/about.qmd
        text: About
        icon: megaphone
      - href: blog/index.qmd
        text: Blog
        icon: pencil
    tools: 
      - icon: github
        href: github.com
      - icon: airplane-engines 
      - text: "<i class='house'></i>"
      
format:
  html:
    backgroundcolor: "#eeffee"
    theme: [cosmo, styles.scss]

    