---
project:
  type: website 
  output-dir: _site
  title: "Insight Brasil" 
  resources: 
    - "!data/**"
  

website:
  title: "Insight Brasil"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  page-footer: "Made with ❤️ and Quarto"
  navbar:
    title: "Insight Brasil"
    left: 
      - text: Home 
        href: index.qmd
        icon: "fa-solid fa-house"

    right:

      - href: pages/about.qmd
        text: Sobre o Insight Brasil
        icon: "fa-solid fa=bullhorn" 

      - href: blog/index.qmd
        text: Blog
        icon: "fa-solid fa-pencil"
    
      - icon: "fa-brands fa-github"
        href: https://github.com 

      - icon: "fa-brands fa-linkedin"
        href: https://linkedin.com/in/williambr
      
      
format:
  html:
    theme: trestles
    css: ["assets/styles.scss","assets/fontawesome.css"] 

    