---
project:
  type: website 
  output-dir: _site
  title: "Insight Brasil" 
  resources: 
    - "!data/**"
  

website:
  title: "Insight Brasil"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  page-footer: "Made with ❤️ and Quarto"
  navbar:
    title: Home
    right:

      - href: pages/about.qmd
        text: Sobre o Insight Brasil
        icon: megaphone
      - href: blog/index.qmd
        text: Blog
        icon: pencil
    tools: 
      - icon: github
        href: github.com
      - icon: airplane-engines 
      - text: "<i class='house'></i>"
      
format:
  html:
    backgroundcolor: "#eeffee"
    theme: [trestles, styles.scss]

    